language: python
python:
  - "3.4"
install:
    - pip install -r requirements.txt
env:
  - DB=postgres
addons:
  postgresql: "9.4"
script:
  - python manage.py collectstatic --no-input
  - coverage run --omit=*/tests/* --source=hc manage.py test
after_success: coveralls
cache: pip
