version: 2
jobs:
  build:
    working_directory: ~/hc-bulls
    docker:
      - image: circleci/python:3.6.4
        environment:
          PIPENV_VENV_IN_PROJECT: true
          DATABASE_URL: postgresql://root@localhost/circle_test?sslmode=disable
      - image: nimbustech/postgres-ssl:9.5
        environment:
          POSTGRES_USER: root
          POSTGRES_DB: circle_test
    steps:
      - checkout
      - run: sudo chown -R circleci:circleci /usr/local/bin
      - run: sudo chown -R circleci:circleci /usr/local/lib/python3.6/site-packages
      - restore_cache:
          key: deps9-{{ .Branch }}
      - run:
          command: |
            sudo pip install pipenv
            pipenv install
            wget -qO- https://cli-assets.heroku.com/install-ubuntu.sh | sh
      - save_cache:
          key: deps9-{{ .Branch }}-{{ checksum "Pipfile.lock" }}
          paths:
            - ".venv"
            - "/usr/local/bin"
            - "/usr/local/lib/python3.6/site-packages"
      - run:
          command: |
            pipenv run "pip install -r requirements.txt"
            pipenv run "python manage.py collectstatic --no-input"
            pipenv run "python manage.py test"
  
  deploy:
    working_directory: ~/hc-bulls
    steps:
      - checkout
      - run:
        command: |
          heroku git:remote -a hc-bullss
          git push --force https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git HEAD:refs/heads/master
          sleep 5  # sleep for 5 seconds to wait for dynos
          heroku restart


workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy:
        requires:
          - build
        filters:
          branches:
            only: develop