# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-05-03 13:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20180503_1013'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='reports_frequency',
            field=models.CharField(default='Monthly', max_length=200),
        ),
        migrations.AlterField(
            model_name='profile',
            name='reports_allowed',
            field=models.BooleanField(default=True),
        ),
    ]
