# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-05-10 13:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_auto_20160415_1824'),
    ]

    operations = [
        migrations.AddField(
            model_name='check',
            name='next_ping',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='check',
            name='status',
            field=models.CharField(choices=[('up', 'Up'), ('down', 'Down'), ('new', 'New'), ('paused', 'Paused'), ('too often', 'Too often')], default='new', max_length=9),
        ),
    ]
